### ISSUE TITLE
Can't run rosnode No module named vl53l0x_msgs.srv._StartRanging

### ISSUE THREAD

**Issue by broadcom9821** [sebastiengemme/vl53l0x#1]
I did sudo setup.py install
and then got this error
Traceback (most recent call last):
  File "/home/pi/catkin_ws/src/vl53l0x-ros/vl53l0x/scripts/vl53l0x_n
ode", line 32, in <module>
    from vl53l0x.tof import VL53L0x
  File "/usr/local/lib/python2.7/dist-packages/vl53l0x/tof.py", line
 38, in <module>
    from vl53l0x_msgs.srv._StartRanging import StartRanging, StartRa
ngingResponse, \
ImportError: No module named vl53l0x_msgs.srv._StartRanging

**Comment by sebastiengemme** [comment]
@broadcom9821 Installing using ```setup.py``` will not build the dependencies, one of which being the message definitions ```vl53l0x_msgs```.
Catkin should be used to build this ROS package, I added the instructions in the [README](https://github.com/sebastiengemme/vl53l0x-ros/blob/master/README.md) file, let me know if you managed to get it working.
