### ISSUE TITLE
Can not run rosnode 

### ISSUE THREAD

**Issue by NAEE09** [sebastiengemme/vl53l0x#2]
Hi!!
I want to use this package but i have an error: No module named VL53L0X.
I already installed the VL53L0X python API on Raspi, but I don't know if I have to install in a specific directory, the library works fine when I execute the example. Any help?

Thank you.

**Comment by sebastiengemme** [comment]
Helo, let me check this more closely, will get back to you

**Comment by sebastiengemme** [comment]
Hello, I added a script called build_dep.sh which should properly build the VL53L0X module and install it. This script needs to be run on the raspberry pi. Let me know if it works.

**Comment by NAEE09** [comment]
Hello, that worked!. Thank you.
